services:
  - type: web
    name: campusgo-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: campusgo-db
          property: connectionString
      - key: FIREBASE_WEB_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: MEDIA_BASE_URL
        sync: false

databases:
  - name: campusgo-db
    plan: free
